//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.ProductServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProduct", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/AddCategory", ReplyAction="http://tempuri.org/IProduct/AddCategoryResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        void AddCategory(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProduct/AddCategory", ReplyAction="http://tempuri.org/IProduct/AddCategoryResponse")]
        System.IAsyncResult BeginAddCategory(string CategoryName, System.AsyncCallback callback, object asyncState);
        
        void EndAddCategory(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/AddProduct", ReplyAction="http://tempuri.org/IProduct/AddProductResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        int AddProduct();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IProduct/AddProduct", ReplyAction="http://tempuri.org/IProduct/AddProductResponse")]
        System.IAsyncResult BeginAddProduct(System.AsyncCallback callback, object asyncState);
        
        int EndAddProduct(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : WindowsClient.ProductServiceReference.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<WindowsClient.ProductServiceReference.IProduct>, WindowsClient.ProductServiceReference.IProduct {
        
        private BeginOperationDelegate onBeginAddCategoryDelegate;
        
        private EndOperationDelegate onEndAddCategoryDelegate;
        
        private System.Threading.SendOrPostCallback onAddCategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddProductDelegate;
        
        private EndOperationDelegate onEndAddProductDelegate;
        
        private System.Threading.SendOrPostCallback onAddProductCompletedDelegate;
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddCategoryCompleted;
        
        public event System.EventHandler<AddProductCompletedEventArgs> AddProductCompleted;
        
        public void AddCategory(string CategoryName) {
            base.Channel.AddCategory(CategoryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddCategory(string CategoryName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCategory(CategoryName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddCategory(System.IAsyncResult result) {
            base.Channel.EndAddCategory(result);
        }
        
        private System.IAsyncResult OnBeginAddCategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string CategoryName = ((string)(inValues[0]));
            return this.BeginAddCategory(CategoryName, callback, asyncState);
        }
        
        private object[] OnEndAddCategory(System.IAsyncResult result) {
            this.EndAddCategory(result);
            return null;
        }
        
        private void OnAddCategoryCompleted(object state) {
            if ((this.AddCategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCategoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCategoryAsync(string CategoryName) {
            this.AddCategoryAsync(CategoryName, null);
        }
        
        public void AddCategoryAsync(string CategoryName, object userState) {
            if ((this.onBeginAddCategoryDelegate == null)) {
                this.onBeginAddCategoryDelegate = new BeginOperationDelegate(this.OnBeginAddCategory);
            }
            if ((this.onEndAddCategoryDelegate == null)) {
                this.onEndAddCategoryDelegate = new EndOperationDelegate(this.OnEndAddCategory);
            }
            if ((this.onAddCategoryCompletedDelegate == null)) {
                this.onAddCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCategoryCompleted);
            }
            base.InvokeAsync(this.onBeginAddCategoryDelegate, new object[] {
                        CategoryName}, this.onEndAddCategoryDelegate, this.onAddCategoryCompletedDelegate, userState);
        }
        
        public int AddProduct() {
            return base.Channel.AddProduct();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddProduct(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddProduct(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndAddProduct(System.IAsyncResult result) {
            return base.Channel.EndAddProduct(result);
        }
        
        private System.IAsyncResult OnBeginAddProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAddProduct(callback, asyncState);
        }
        
        private object[] OnEndAddProduct(System.IAsyncResult result) {
            int retVal = this.EndAddProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddProductCompleted(object state) {
            if ((this.AddProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddProductCompleted(this, new AddProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddProductAsync() {
            this.AddProductAsync(null);
        }
        
        public void AddProductAsync(object userState) {
            if ((this.onBeginAddProductDelegate == null)) {
                this.onBeginAddProductDelegate = new BeginOperationDelegate(this.OnBeginAddProduct);
            }
            if ((this.onEndAddProductDelegate == null)) {
                this.onEndAddProductDelegate = new EndOperationDelegate(this.OnEndAddProduct);
            }
            if ((this.onAddProductCompletedDelegate == null)) {
                this.onAddProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddProductCompleted);
            }
            base.InvokeAsync(this.onBeginAddProductDelegate, null, this.onEndAddProductDelegate, this.onAddProductCompletedDelegate, userState);
        }
    }
}
